from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from cryoet_agent.agent.schemas import WorkflowPlan
from cryoet_agent.config import PLAN_DIR_NAME, workspace_root


def write_plan_files(plan: WorkflowPlan) -> tuple[Path, Path]:
    root = workspace_root()
    plan_dir = root / PLAN_DIR_NAME
    plan_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    stem = f"workflow-{timestamp}"
    markdown_path = plan_dir / f"{stem}.md"
    json_path = plan_dir / f"{stem}.json"
    markdown_path.write_text(render_markdown(plan), encoding="utf-8")
    json_path.write_text(json.dumps(plan.model_dump(), indent=2), encoding="utf-8")
    return markdown_path, json_path


def render_markdown(plan: WorkflowPlan) -> str:
    lines = [
        f"# CryoET Workflow Plan",
        "",
        f"**Goal**: {plan.goal}",
        f"**Workspace**: `{plan.workspace}`",
        f"**Dataset Path**: `{plan.dataset_path}`",
        f"**Generated By**: `{plan.generated_by}`",
        "",
        "## Summary",
        plan.summary,
        "",
    ]

    if plan.findings:
        lines.extend(["## What I Found", *[f"- {item}" for item in plan.findings], ""])
    if plan.assumptions:
        lines.extend(["## Assumptions", *[f"- {item}" for item in plan.assumptions], ""])
    if plan.alternative_options:
        lines.extend(["## Alternative Options", *[f"- {item}" for item in plan.alternative_options], ""])

    lines.append("## Step-by-Step Plan")
    lines.append("")
    for index, step in enumerate(plan.steps, start=1):
        lines.append(f"### Step {index}. {step.title}")
        lines.append(f"- Status: `{step.status}`")
        lines.append(f"- Purpose: {step.purpose}")
        lines.append(f"- Software: {', '.join(step.software) if step.software else 'Not specified'}")
        lines.append(f"- Inputs: {', '.join(step.inputs) if step.inputs else 'Not specified'}")
        lines.append(f"- Outputs: {', '.join(step.outputs) if step.outputs else 'Not specified'}")
        lines.append(f"- Why: {step.rationale}")
        if step.suggested_parameters:
            lines.append("- Suggested parameters:")
            for name, value in step.suggested_parameters.items():
                lines.append(f"  - `{name}`: {value}")
        if step.checks:
            lines.append("- Check before continuing:")
            for item in step.checks:
                lines.append(f"  - {item}")
        if step.risks:
            lines.append("- Risks:")
            for item in step.risks:
                lines.append(f"  - {item}")
        lines.append("")

    if plan.unresolved_questions:
        lines.extend(["## Unresolved Questions", *[f"- {item}" for item in plan.unresolved_questions], ""])
    if plan.relevant_skills:
        lines.extend(["## Relevant Skills", *[f"- {item}" for item in plan.relevant_skills], ""])
    return "\n".join(lines).rstrip() + "\n"

